// <auto-generated />
using Booking.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Booking.DAL.Migrations
{
    [DbContext(typeof(BookingContext))]
    partial class BookingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Booking.Common.Models.City", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryID");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.HasIndex("CountryID");

                    b.ToTable("City");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CountryID = 1,
                            Name = "City_Sudan"
                        },
                        new
                        {
                            ID = 2,
                            CountryID = 2,
                            Name = "City_Gabon"
                        },
                        new
                        {
                            ID = 3,
                            CountryID = 3,
                            Name = "City_Korea"
                        },
                        new
                        {
                            ID = 4,
                            CountryID = 4,
                            Name = "City_Guinea-Bissau"
                        },
                        new
                        {
                            ID = 5,
                            CountryID = 5,
                            Name = "City_China"
                        },
                        new
                        {
                            ID = 6,
                            CountryID = 6,
                            Name = "City_Somalia"
                        },
                        new
                        {
                            ID = 7,
                            CountryID = 7,
                            Name = "City_Angola"
                        },
                        new
                        {
                            ID = 8,
                            CountryID = 8,
                            Name = "City_Nigeria"
                        },
                        new
                        {
                            ID = 9,
                            CountryID = 9,
                            Name = "City_Canada"
                        },
                        new
                        {
                            ID = 10,
                            CountryID = 10,
                            Name = "City_Botswana"
                        },
                        new
                        {
                            ID = 11,
                            CountryID = 11,
                            Name = "City_Lithuania"
                        },
                        new
                        {
                            ID = 12,
                            CountryID = 12,
                            Name = "City_Iceland"
                        },
                        new
                        {
                            ID = 13,
                            CountryID = 13,
                            Name = "City_Guinea"
                        },
                        new
                        {
                            ID = 14,
                            CountryID = 14,
                            Name = "City_Chad"
                        },
                        new
                        {
                            ID = 15,
                            CountryID = 15,
                            Name = "City_Mali"
                        },
                        new
                        {
                            ID = 16,
                            CountryID = 16,
                            Name = "City_Tanzania"
                        },
                        new
                        {
                            ID = 17,
                            CountryID = 17,
                            Name = "City_Central African Republic"
                        },
                        new
                        {
                            ID = 18,
                            CountryID = 18,
                            Name = "City_Colombia"
                        },
                        new
                        {
                            ID = 19,
                            CountryID = 19,
                            Name = "City_Guatemala"
                        },
                        new
                        {
                            ID = 20,
                            CountryID = 20,
                            Name = "City_Equatorial Guinea"
                        },
                        new
                        {
                            ID = 21,
                            CountryID = 21,
                            Name = "City_Oman"
                        },
                        new
                        {
                            ID = 22,
                            CountryID = 22,
                            Name = "City_Gambia"
                        },
                        new
                        {
                            ID = 23,
                            CountryID = 23,
                            Name = "City_Libya"
                        },
                        new
                        {
                            ID = 24,
                            CountryID = 24,
                            Name = "City_Zimbabwe"
                        },
                        new
                        {
                            ID = 25,
                            CountryID = 25,
                            Name = "City_Malawi"
                        },
                        new
                        {
                            ID = 26,
                            CountryID = 26,
                            Name = "City_Ethiopia"
                        },
                        new
                        {
                            ID = 27,
                            CountryID = 27,
                            Name = "City_Pakistan"
                        },
                        new
                        {
                            ID = 28,
                            CountryID = 28,
                            Name = "City_Senegal"
                        },
                        new
                        {
                            ID = 29,
                            CountryID = 29,
                            Name = "City_New Zealand"
                        },
                        new
                        {
                            ID = 30,
                            CountryID = 30,
                            Name = "City_Ghana"
                        },
                        new
                        {
                            ID = 31,
                            CountryID = 31,
                            Name = "City_Argentina"
                        },
                        new
                        {
                            ID = 32,
                            CountryID = 32,
                            Name = "City_Philippines"
                        },
                        new
                        {
                            ID = 33,
                            CountryID = 33,
                            Name = "City_Cameroon"
                        },
                        new
                        {
                            ID = 34,
                            CountryID = 34,
                            Name = "City_Mauritania"
                        },
                        new
                        {
                            ID = 35,
                            CountryID = 35,
                            Name = "City_Iraq"
                        },
                        new
                        {
                            ID = 36,
                            CountryID = 36,
                            Name = "City_Malta"
                        },
                        new
                        {
                            ID = 37,
                            CountryID = 37,
                            Name = "City_Mozambique"
                        },
                        new
                        {
                            ID = 38,
                            CountryID = 38,
                            Name = "City_Syria"
                        },
                        new
                        {
                            ID = 39,
                            CountryID = 39,
                            Name = "City_Benin"
                        },
                        new
                        {
                            ID = 40,
                            CountryID = 40,
                            Name = "City_Israel"
                        },
                        new
                        {
                            ID = 41,
                            CountryID = 41,
                            Name = "City_Bosnia and Herzegovina"
                        },
                        new
                        {
                            ID = 42,
                            CountryID = 42,
                            Name = "City_Estonia"
                        },
                        new
                        {
                            ID = 43,
                            CountryID = 43,
                            Name = "City_Lesotho"
                        },
                        new
                        {
                            ID = 44,
                            CountryID = 44,
                            Name = "City_United Arab Emirates"
                        },
                        new
                        {
                            ID = 45,
                            CountryID = 45,
                            Name = "City_Austria"
                        },
                        new
                        {
                            ID = 46,
                            CountryID = 46,
                            Name = "City_Belgium"
                        },
                        new
                        {
                            ID = 47,
                            CountryID = 47,
                            Name = "City_Bulgaria"
                        },
                        new
                        {
                            ID = 48,
                            CountryID = 48,
                            Name = "City_Switzerland"
                        },
                        new
                        {
                            ID = 49,
                            CountryID = 49,
                            Name = "City_Serbia"
                        },
                        new
                        {
                            ID = 50,
                            CountryID = 50,
                            Name = "City_Czech Republic"
                        },
                        new
                        {
                            ID = 51,
                            CountryID = 51,
                            Name = "City_Germany"
                        },
                        new
                        {
                            ID = 52,
                            CountryID = 52,
                            Name = "City_Denmark"
                        },
                        new
                        {
                            ID = 53,
                            CountryID = 53,
                            Name = "City_Spain"
                        },
                        new
                        {
                            ID = 54,
                            CountryID = 54,
                            Name = "City_Finland"
                        },
                        new
                        {
                            ID = 55,
                            CountryID = 55,
                            Name = "City_France"
                        },
                        new
                        {
                            ID = 56,
                            CountryID = 56,
                            Name = "City_United Kingdom"
                        },
                        new
                        {
                            ID = 57,
                            CountryID = 57,
                            Name = "City_Greece"
                        },
                        new
                        {
                            ID = 58,
                            CountryID = 58,
                            Name = "City_Hong Kong"
                        },
                        new
                        {
                            ID = 59,
                            CountryID = 59,
                            Name = "City_Croatia"
                        },
                        new
                        {
                            ID = 60,
                            CountryID = 60,
                            Name = "City_Hungary"
                        },
                        new
                        {
                            ID = 61,
                            CountryID = 61,
                            Name = "City_Ireland"
                        },
                        new
                        {
                            ID = 62,
                            CountryID = 62,
                            Name = "City_India"
                        },
                        new
                        {
                            ID = 63,
                            CountryID = 63,
                            Name = "City_Italy"
                        },
                        new
                        {
                            ID = 64,
                            CountryID = 64,
                            Name = "City_Japan"
                        },
                        new
                        {
                            ID = 65,
                            CountryID = 65,
                            Name = "City_Kazakhstan"
                        },
                        new
                        {
                            ID = 66,
                            CountryID = 66,
                            Name = "City_Luxembourg"
                        },
                        new
                        {
                            ID = 67,
                            CountryID = 67,
                            Name = "City_Morocco"
                        },
                        new
                        {
                            ID = 68,
                            CountryID = 68,
                            Name = "City_Netherlands"
                        },
                        new
                        {
                            ID = 69,
                            CountryID = 69,
                            Name = "City_Norway"
                        },
                        new
                        {
                            ID = 70,
                            CountryID = 70,
                            Name = "City_Poland"
                        },
                        new
                        {
                            ID = 71,
                            CountryID = 71,
                            Name = "City_Portugal"
                        },
                        new
                        {
                            ID = 72,
                            CountryID = 72,
                            Name = "City_Romania"
                        },
                        new
                        {
                            ID = 73,
                            CountryID = 73,
                            Name = "City_Russian Federation"
                        },
                        new
                        {
                            ID = 74,
                            CountryID = 74,
                            Name = "City_Sweden"
                        },
                        new
                        {
                            ID = 75,
                            CountryID = 75,
                            Name = "City_Singapore"
                        },
                        new
                        {
                            ID = 76,
                            CountryID = 76,
                            Name = "City_Slovenia"
                        },
                        new
                        {
                            ID = 77,
                            CountryID = 77,
                            Name = "City_Slovakia"
                        },
                        new
                        {
                            ID = 78,
                            CountryID = 78,
                            Name = "City_Tunisia"
                        },
                        new
                        {
                            ID = 79,
                            CountryID = 79,
                            Name = "City_Turkey"
                        },
                        new
                        {
                            ID = 80,
                            CountryID = 80,
                            Name = "City_Taiwan"
                        },
                        new
                        {
                            ID = 81,
                            CountryID = 81,
                            Name = "City_Ukraine"
                        },
                        new
                        {
                            ID = 82,
                            CountryID = 82,
                            Name = "City_United States"
                        },
                        new
                        {
                            ID = 83,
                            CountryID = 83,
                            Name = "City_Uzbekistan"
                        },
                        new
                        {
                            ID = 84,
                            CountryID = 84,
                            Name = "City_South Africa"
                        },
                        new
                        {
                            ID = 85,
                            CountryID = 85,
                            Name = "City_Egypt"
                        },
                        new
                        {
                            ID = 86,
                            CountryID = 86,
                            Name = "City_Mexico"
                        },
                        new
                        {
                            ID = 87,
                            CountryID = 87,
                            Name = "City_Brazil"
                        },
                        new
                        {
                            ID = 88,
                            CountryID = 88,
                            Name = "City_Lebanon"
                        },
                        new
                        {
                            ID = 89,
                            CountryID = 89,
                            Name = "City_Kuwait"
                        },
                        new
                        {
                            ID = 90,
                            CountryID = 90,
                            Name = "City_Uruguay"
                        },
                        new
                        {
                            ID = 91,
                            CountryID = 91,
                            Name = "City_Sierra Leone"
                        },
                        new
                        {
                            ID = 92,
                            CountryID = 92,
                            Name = "City_Togo"
                        },
                        new
                        {
                            ID = 93,
                            CountryID = 93,
                            Name = "City_Rwanda"
                        },
                        new
                        {
                            ID = 94,
                            CountryID = 94,
                            Name = "City_Burundi"
                        },
                        new
                        {
                            ID = 95,
                            CountryID = 95,
                            Name = "City_Saudi Arabia"
                        },
                        new
                        {
                            ID = 96,
                            CountryID = 96,
                            Name = "City_Yemen"
                        },
                        new
                        {
                            ID = 97,
                            CountryID = 97,
                            Name = "City_Albania"
                        },
                        new
                        {
                            ID = 98,
                            CountryID = 98,
                            Name = "City_Ivory Coast"
                        },
                        new
                        {
                            ID = 99,
                            CountryID = 99,
                            Name = "City_Kirkistan"
                        },
                        new
                        {
                            ID = 100,
                            CountryID = 100,
                            Name = "City_Western Sahara"
                        },
                        new
                        {
                            ID = 101,
                            CountryID = 101,
                            Name = "City_Kenya"
                        },
                        new
                        {
                            ID = 102,
                            CountryID = 102,
                            Name = "City_Eritrea"
                        },
                        new
                        {
                            ID = 103,
                            CountryID = 103,
                            Name = "City_Bahrain"
                        },
                        new
                        {
                            ID = 104,
                            CountryID = 104,
                            Name = "City_Uganda"
                        },
                        new
                        {
                            ID = 105,
                            CountryID = 105,
                            Name = "City_Madagascar"
                        },
                        new
                        {
                            ID = 106,
                            CountryID = 106,
                            Name = "City_Republic of Macedonia"
                        },
                        new
                        {
                            ID = 107,
                            CountryID = 107,
                            Name = "City_Burkina Faso"
                        },
                        new
                        {
                            ID = 108,
                            CountryID = 108,
                            Name = "City_Afghanistan"
                        },
                        new
                        {
                            ID = 109,
                            CountryID = 109,
                            Name = "City_Zambia"
                        },
                        new
                        {
                            ID = 110,
                            CountryID = 110,
                            Name = "City_Swaziland"
                        },
                        new
                        {
                            ID = 111,
                            CountryID = 111,
                            Name = "City_Algeria"
                        },
                        new
                        {
                            ID = 112,
                            CountryID = 112,
                            Name = "City_Niger"
                        },
                        new
                        {
                            ID = 113,
                            CountryID = 113,
                            Name = "City_Qatar"
                        },
                        new
                        {
                            ID = 114,
                            CountryID = 114,
                            Name = "City_Palestine"
                        },
                        new
                        {
                            ID = 115,
                            CountryID = 115,
                            Name = "City_Chile"
                        },
                        new
                        {
                            ID = 116,
                            CountryID = 116,
                            Name = "City_Jordan"
                        },
                        new
                        {
                            ID = 117,
                            CountryID = 117,
                            Name = "City_Iran"
                        },
                        new
                        {
                            ID = 118,
                            CountryID = 118,
                            Name = "City_Australia"
                        },
                        new
                        {
                            ID = 119,
                            CountryID = 119,
                            Name = "City_Liberia"
                        },
                        new
                        {
                            ID = 120,
                            CountryID = 120,
                            Name = "City_Latvia"
                        });
                });

            modelBuilder.Entity("Booking.Common.Models.Country", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Sudan"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Gabon"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Korea"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            ID = 5,
                            Name = "China"
                        },
                        new
                        {
                            ID = 6,
                            Name = "Somalia"
                        },
                        new
                        {
                            ID = 7,
                            Name = "Angola"
                        },
                        new
                        {
                            ID = 8,
                            Name = "Nigeria"
                        },
                        new
                        {
                            ID = 9,
                            Name = "Canada"
                        },
                        new
                        {
                            ID = 10,
                            Name = "Botswana"
                        },
                        new
                        {
                            ID = 11,
                            Name = "Lithuania"
                        },
                        new
                        {
                            ID = 12,
                            Name = "Iceland"
                        },
                        new
                        {
                            ID = 13,
                            Name = "Guinea"
                        },
                        new
                        {
                            ID = 14,
                            Name = "Chad"
                        },
                        new
                        {
                            ID = 15,
                            Name = "Mali"
                        },
                        new
                        {
                            ID = 16,
                            Name = "Tanzania"
                        },
                        new
                        {
                            ID = 17,
                            Name = "Central African Republic"
                        },
                        new
                        {
                            ID = 18,
                            Name = "Colombia"
                        },
                        new
                        {
                            ID = 19,
                            Name = "Guatemala"
                        },
                        new
                        {
                            ID = 20,
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            ID = 21,
                            Name = "Oman"
                        },
                        new
                        {
                            ID = 22,
                            Name = "Gambia"
                        },
                        new
                        {
                            ID = 23,
                            Name = "Libya"
                        },
                        new
                        {
                            ID = 24,
                            Name = "Zimbabwe"
                        },
                        new
                        {
                            ID = 25,
                            Name = "Malawi"
                        },
                        new
                        {
                            ID = 26,
                            Name = "Ethiopia"
                        },
                        new
                        {
                            ID = 27,
                            Name = "Pakistan"
                        },
                        new
                        {
                            ID = 28,
                            Name = "Senegal"
                        },
                        new
                        {
                            ID = 29,
                            Name = "New Zealand"
                        },
                        new
                        {
                            ID = 30,
                            Name = "Ghana"
                        },
                        new
                        {
                            ID = 31,
                            Name = "Argentina"
                        },
                        new
                        {
                            ID = 32,
                            Name = "Philippines"
                        },
                        new
                        {
                            ID = 33,
                            Name = "Cameroon"
                        },
                        new
                        {
                            ID = 34,
                            Name = "Mauritania"
                        },
                        new
                        {
                            ID = 35,
                            Name = "Iraq"
                        },
                        new
                        {
                            ID = 36,
                            Name = "Malta"
                        },
                        new
                        {
                            ID = 37,
                            Name = "Mozambique"
                        },
                        new
                        {
                            ID = 38,
                            Name = "Syria"
                        },
                        new
                        {
                            ID = 39,
                            Name = "Benin"
                        },
                        new
                        {
                            ID = 40,
                            Name = "Israel"
                        },
                        new
                        {
                            ID = 41,
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            ID = 42,
                            Name = "Estonia"
                        },
                        new
                        {
                            ID = 43,
                            Name = "Lesotho"
                        },
                        new
                        {
                            ID = 44,
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            ID = 45,
                            Name = "Austria"
                        },
                        new
                        {
                            ID = 46,
                            Name = "Belgium"
                        },
                        new
                        {
                            ID = 47,
                            Name = "Bulgaria"
                        },
                        new
                        {
                            ID = 48,
                            Name = "Switzerland"
                        },
                        new
                        {
                            ID = 49,
                            Name = "Serbia"
                        },
                        new
                        {
                            ID = 50,
                            Name = "Czech Republic"
                        },
                        new
                        {
                            ID = 51,
                            Name = "Germany"
                        },
                        new
                        {
                            ID = 52,
                            Name = "Denmark"
                        },
                        new
                        {
                            ID = 53,
                            Name = "Spain"
                        },
                        new
                        {
                            ID = 54,
                            Name = "Finland"
                        },
                        new
                        {
                            ID = 55,
                            Name = "France"
                        },
                        new
                        {
                            ID = 56,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            ID = 57,
                            Name = "Greece"
                        },
                        new
                        {
                            ID = 58,
                            Name = "Hong Kong"
                        },
                        new
                        {
                            ID = 59,
                            Name = "Croatia"
                        },
                        new
                        {
                            ID = 60,
                            Name = "Hungary"
                        },
                        new
                        {
                            ID = 61,
                            Name = "Ireland"
                        },
                        new
                        {
                            ID = 62,
                            Name = "India"
                        },
                        new
                        {
                            ID = 63,
                            Name = "Italy"
                        },
                        new
                        {
                            ID = 64,
                            Name = "Japan"
                        },
                        new
                        {
                            ID = 65,
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            ID = 66,
                            Name = "Luxembourg"
                        },
                        new
                        {
                            ID = 67,
                            Name = "Morocco"
                        },
                        new
                        {
                            ID = 68,
                            Name = "Netherlands"
                        },
                        new
                        {
                            ID = 69,
                            Name = "Norway"
                        },
                        new
                        {
                            ID = 70,
                            Name = "Poland"
                        },
                        new
                        {
                            ID = 71,
                            Name = "Portugal"
                        },
                        new
                        {
                            ID = 72,
                            Name = "Romania"
                        },
                        new
                        {
                            ID = 73,
                            Name = "Russian Federation"
                        },
                        new
                        {
                            ID = 74,
                            Name = "Sweden"
                        },
                        new
                        {
                            ID = 75,
                            Name = "Singapore"
                        },
                        new
                        {
                            ID = 76,
                            Name = "Slovenia"
                        },
                        new
                        {
                            ID = 77,
                            Name = "Slovakia"
                        },
                        new
                        {
                            ID = 78,
                            Name = "Tunisia"
                        },
                        new
                        {
                            ID = 79,
                            Name = "Turkey"
                        },
                        new
                        {
                            ID = 80,
                            Name = "Taiwan"
                        },
                        new
                        {
                            ID = 81,
                            Name = "Ukraine"
                        },
                        new
                        {
                            ID = 82,
                            Name = "United States"
                        },
                        new
                        {
                            ID = 83,
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            ID = 84,
                            Name = "South Africa"
                        },
                        new
                        {
                            ID = 85,
                            Name = "Egypt"
                        },
                        new
                        {
                            ID = 86,
                            Name = "Mexico"
                        },
                        new
                        {
                            ID = 87,
                            Name = "Brazil"
                        },
                        new
                        {
                            ID = 88,
                            Name = "Lebanon"
                        },
                        new
                        {
                            ID = 89,
                            Name = "Kuwait"
                        },
                        new
                        {
                            ID = 90,
                            Name = "Uruguay"
                        },
                        new
                        {
                            ID = 91,
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            ID = 92,
                            Name = "Togo"
                        },
                        new
                        {
                            ID = 93,
                            Name = "Rwanda"
                        },
                        new
                        {
                            ID = 94,
                            Name = "Burundi"
                        },
                        new
                        {
                            ID = 95,
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            ID = 96,
                            Name = "Yemen"
                        },
                        new
                        {
                            ID = 97,
                            Name = "Albania"
                        },
                        new
                        {
                            ID = 98,
                            Name = "Ivory Coast"
                        },
                        new
                        {
                            ID = 99,
                            Name = "Kirkistan"
                        },
                        new
                        {
                            ID = 100,
                            Name = "Western Sahara"
                        },
                        new
                        {
                            ID = 101,
                            Name = "Kenya"
                        },
                        new
                        {
                            ID = 102,
                            Name = "Eritrea"
                        },
                        new
                        {
                            ID = 103,
                            Name = "Bahrain"
                        },
                        new
                        {
                            ID = 104,
                            Name = "Uganda"
                        },
                        new
                        {
                            ID = 105,
                            Name = "Madagascar"
                        },
                        new
                        {
                            ID = 106,
                            Name = "Republic of Macedonia"
                        },
                        new
                        {
                            ID = 107,
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            ID = 108,
                            Name = "Afghanistan"
                        },
                        new
                        {
                            ID = 109,
                            Name = "Zambia"
                        },
                        new
                        {
                            ID = 110,
                            Name = "Swaziland"
                        },
                        new
                        {
                            ID = 111,
                            Name = "Algeria"
                        },
                        new
                        {
                            ID = 112,
                            Name = "Niger"
                        },
                        new
                        {
                            ID = 113,
                            Name = "Qatar"
                        },
                        new
                        {
                            ID = 114,
                            Name = "Palestine"
                        },
                        new
                        {
                            ID = 115,
                            Name = "Chile"
                        },
                        new
                        {
                            ID = 116,
                            Name = "Jordan"
                        },
                        new
                        {
                            ID = 117,
                            Name = "Iran"
                        },
                        new
                        {
                            ID = 118,
                            Name = "Australia"
                        },
                        new
                        {
                            ID = 119,
                            Name = "Liberia"
                        },
                        new
                        {
                            ID = 120,
                            Name = "Latvia"
                        });
                });

            modelBuilder.Entity("Booking.Common.Models.Hotel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityID");

                    b.Property<string>("Coordinates");

                    b.Property<string>("Name");

                    b.Property<int>("RaitingID");

                    b.HasKey("ID");

                    b.HasIndex("CityID");

                    b.HasIndex("RaitingID");

                    b.ToTable("Hotel");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CityID = 1,
                            Coordinates = " ",
                            Name = "Hotel_1 star",
                            RaitingID = 1
                        },
                        new
                        {
                            ID = 2,
                            CityID = 2,
                            Coordinates = " ",
                            Name = "Hotel_2 star",
                            RaitingID = 2
                        },
                        new
                        {
                            ID = 3,
                            CityID = 3,
                            Coordinates = " ",
                            Name = "Hotel_3 star",
                            RaitingID = 3
                        },
                        new
                        {
                            ID = 4,
                            CityID = 4,
                            Coordinates = " ",
                            Name = "Hotel_4 star",
                            RaitingID = 4
                        },
                        new
                        {
                            ID = 5,
                            CityID = 5,
                            Coordinates = " ",
                            Name = "Hotel_5 star",
                            RaitingID = 5
                        });
                });

            modelBuilder.Entity("Booking.Common.Models.Raiting", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.HasKey("ID");

                    b.ToTable("Raiting");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "1 star"
                        },
                        new
                        {
                            ID = 2,
                            Description = "2 star"
                        },
                        new
                        {
                            ID = 3,
                            Description = "3 star"
                        },
                        new
                        {
                            ID = 4,
                            Description = "4 star"
                        },
                        new
                        {
                            ID = 5,
                            Description = "5 star"
                        });
                });

            modelBuilder.Entity("Booking.Common.Models.Role", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.HasKey("ID");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "User"
                        },
                        new
                        {
                            ID = 2,
                            Description = "Administrator"
                        });
                });

            modelBuilder.Entity("Booking.Common.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Passport");

                    b.Property<int>("RoleID");

                    b.HasKey("ID");

                    b.HasIndex("RoleID");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "email1@gmail.com",
                            FirstName = "FirstName1",
                            LastName = "LastName1",
                            Passport = "11 11 111111",
                            RoleID = 1
                        },
                        new
                        {
                            ID = 2,
                            Email = "email2@gmail.com",
                            FirstName = "FirstName2",
                            LastName = "LastName2",
                            Passport = "22 22 222222",
                            RoleID = 1
                        },
                        new
                        {
                            ID = 3,
                            Email = "email3@gmail.com",
                            FirstName = "FirstName3",
                            LastName = "LastName3",
                            Passport = "33 33 333333",
                            RoleID = 1
                        },
                        new
                        {
                            ID = 4,
                            Email = "john.doe@gmail.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Passport = "44 44 444444",
                            RoleID = 2
                        });
                });

            modelBuilder.Entity("Booking.Common.Models.City", b =>
                {
                    b.HasOne("Booking.Common.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Booking.Common.Models.Hotel", b =>
                {
                    b.HasOne("Booking.Common.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Booking.Common.Models.Raiting", "Raiting")
                        .WithMany()
                        .HasForeignKey("RaitingID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Booking.Common.Models.User", b =>
                {
                    b.HasOne("Booking.Common.Models.Role", "Roles")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
